### ISSUE TITLE
add new fields

### ISSUE THREAD

**Issue by Praesidiarius** [OnePlc/PLC_X_Contact_History#1]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | yes/no

#### Summary

Add new fields to _simple.sql 

- type_idfs (select to tag "type") ( add new tag "type" )
- date (datetime)
- emotion_idfs ( => @Praesidiarius )

**Comment by JBinggi** [comment]
new field type_idfs and date added : 
96c1619
